import {useEffect,useRef,useState} from 'react';
import {SpeakButton,SpeechControls} from '../speech/Controls';
import {plainSegments} from '../speech/content';
import storyTemplate from './stories/story-tide-letter.json';
import juniorTemplate from './junior/junior-cold-cup.json';
const storyFiles=import.meta.glob<{default:typeof storyTemplate}>('./stories/*.json',{eager:true});
const juniorFiles=import.meta.glob<{default:typeof juniorTemplate}>('./junior/*.json',{eager:true});
export const stories=Object.values(storyFiles).map(x=>x.default).filter(x=>x.status==="published").sort((a,b)=>a.order-b.order);
export const juniors=Object.values(juniorFiles).map(x=>x.default).filter(x=>x.status==="published");
export const newReadings=[...stories.map(s=>({id:s.id,title:s.title,text:[s.summary,...s.paragraphs].join(' '),theme:s.theme,grade:s.grade,image:s.image,imageAlt:s.imageAlt,href:'#stories/'+s.id})),...juniors.map(s=>({id:s.id,title:s.title,text:s.paragraphs.join(' '),theme:s.theme,grade:s.grade,image:s.image,imageAlt:s.imageAlt,href:'#junior/'+s.id}))];
type Reading=typeof stories[number]|typeof juniors[number];
type ReadingMemory={positions:Record<string,number>;done:string[];zhuyin:boolean};
const empty:ReadingMemory={positions:{},done:[],zhuyin:true};
function load():ReadingMemory{try{const x=JSON.parse(localStorage.getItem('question-planet-readings-v1')||'null');return {positions:x?.positions&&typeof x.positions==='object'?x.positions:{},done:Array.isArray(x?.done)?x.done:[],zhuyin:x?.zhuyin!==false}}catch{return empty}}
function store(x:ReadingMemory){try{localStorage.setItem('question-planet-readings-v1',JSON.stringify(x))}catch{/* 閱讀功能仍可使用 */}}
function savedIds():string[]{try{const x=JSON.parse(localStorage.getItem('explorer-magazine-v1')||'{}');return Array.isArray(x.saved)?x.saved:[]}catch{return []}}
export function Phonetic({text,annotations,show}:{text:string;annotations:Record<string,string[]>;show:boolean}){if(!show)return <>{text}</>;let n=0;const z=annotations[text];if(!z)return <>{text}</>;return <span className="ruby-line" aria-label={text}>{[...text].map((c,i)=>/\p{Script=Han}/u.test(c)?<ruby aria-hidden="true" key={i}>{c}<rp>（</rp><rt>{z[n++]}</rt><rp>）</rp></ruby>:<span aria-hidden="true" key={i}>{c}</span>)}</span>}
export default function ReadingLibrary({hash}:{hash:string}){
 const junior=hash.startsWith('#junior'),entries=junior?juniors:stories,id=hash.split('/')[1];const item:Reading|undefined=entries.find(x=>x.id===id);
 const [memory,setMemory]=useState(load),[query,setQuery]=useState(''),[answer,setAnswer]=useState<number|null>(null),[saved,setSaved]=useState(savedIds),[size,setSize]=useState(()=>{try{return JSON.parse(localStorage.getItem('explorer-magazine-v1')||'{}').size||22}catch{return 22}});
 const anchor=useRef<HTMLHeadingElement>(null);
 useEffect(()=>{
  if(!item)return;let timer:ReturnType<typeof setTimeout>|undefined;
  const remember=()=>{clearTimeout(timer);timer=setTimeout(()=>{if(window.scrollY<200)return;const blocks=[...document.querySelectorAll<HTMLElement>('.book-paragraph')];let position=0;blocks.forEach((p,i)=>{if(p.getBoundingClientRect().top<innerHeight*.45)position=i});setMemory(old=>{if(old.positions[item.id]===position)return old;const next={...old,positions:{...old.positions,[item.id]:position}};store(next);return next});},180)};
  window.addEventListener('scroll',remember,{passive:true});return()=>{clearTimeout(timer);window.removeEventListener('scroll',remember)};
 },[item]);
 useEffect(()=>{setAnswer(null);anchor.current?.focus({preventScroll:true});window.scrollTo(0,0)},[hash]);
 const update=(x:Partial<ReadingMemory>)=>setMemory(old=>{const next={...old,...x};store(next);return next});
 function bookmark(){if(!item)return;const next=saved.includes(item.id)?saved.filter(x=>x!==item.id):[...saved,item.id];setSaved(next);try{const old=JSON.parse(localStorage.getItem('explorer-magazine-v1')||'{}');localStorage.setItem('explorer-magazine-v1',JSON.stringify({...old,saved:next}))}catch{/* 無儲存權限時仍可閱讀 */}}
 const say=(t:string,key:string)=>plainSegments(t,key);
 const show=(t:string)=>item&&'annotated'in item?<Phonetic text={t} annotations={item.annotated as Record<string,string[]>} show={memory.zhuyin}/>:t;
 return <div className={'new-reading-library '+(item?'book-open':'book-catalog')}><header className="book-header"><a href="#">← 問號星球首頁</a><nav><a href="#stories">故事館</a><a href="#junior">一二年級</a><a href="#saved">收藏</a><a href="#search">搜尋</a></nav></header>
 {!item?<main><p className="book-eyebrow">{junior?'第一期 · 看見生活的小發現':'STORIES / LISTEN / IMAGINE'}</p><h1 ref={anchor} tabIndex={-1}>{junior?'一、二年級閱讀':'故事館：每一種想像，都有入口'}</h1><p>{junior?'四篇完整讀物。注音可以開關，聽讀也由你決定。':'16 篇完整短篇。慢慢讀，也可以聽完一個故事。年級是建議，歡迎自由探索。'}</p>{id&&<p role="status">找不到這篇讀物，請從目錄選一篇。</p>}<label className="book-search">找讀物<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="故事標題、主題或內文"/></label><div className="book-grid">{entries.filter(s=>[s.title,s.theme,...s.paragraphs].join(' ').includes(query)).map(s=><a className="book-card" key={s.id} href={(junior?'#junior/':'#stories/')+s.id}><img src={s.image} alt={s.imageAlt} loading="lazy"/><small>{s.theme} · {s.grade}</small><h2>{s.title}</h2><p>{'summary'in s?s.summary:s.paragraphs[0]}</p><span>{memory.done.includes(s.id)?'已讀完 · 再讀一次':memory.positions[s.id]!==undefined?'繼續閱讀 →':'開始閱讀 →'}</span></a>)}</div>{!entries.some(s=>[s.title,s.theme,...s.paragraphs].join(' ').includes(query))&&<p>沒有符合的讀物，換個關鍵字試試。</p>}</main>:<main className="book-reader" style={{fontSize:[20,22,25,28,30].includes(size)?size:22}}><a href={junior?'#junior':'#stories'}>← 回本區目錄</a><p className="book-eyebrow">{item.grade} · {item.theme}</p><h1 ref={anchor} tabIndex={-1} data-speech-id="book-title">{show(item.title)}</h1><img className="book-cover" src={item.image} alt={item.imageAlt}/><div className="book-tools"><SpeakButton label={junior?'聽這一篇':'聽完整故事'} segments={[...say(item.title,'book-title'),...item.paragraphs.flatMap((p,i)=>say(p,'book-p-'+i))]}/><button onClick={bookmark} aria-pressed={saved.includes(item.id)}>{saved.includes(item.id)?'已收藏 ✓':'收藏這篇'}</button>{junior&&<button aria-pressed={memory.zhuyin} onClick={()=>update({zhuyin:!memory.zhuyin})}>注音：{memory.zhuyin?'開':'關'}</button>}<label>字級 <select aria-label="讀物字級" value={size} onChange={e=>{const n=Number(e.target.value);setSize(n);try{const x=JSON.parse(localStorage.getItem('explorer-magazine-v1')||'{}');localStorage.setItem('explorer-magazine-v1',JSON.stringify({...x,size:n}))}catch{/* 可繼續閱讀 */}}}>{[20,22,25,28].map(n=><option value={n} key={n}>{n}</option>)}</select></label></div><SpeechControls/><p className="voice-note">使用裝置內建語音，聲音因瀏覽器而異；不是預錄真人音檔，離線可用性依裝置而定。</p>
 {memory.positions[item.id]!==undefined&&<button className="book-resume" onClick={()=>document.getElementById('book-p-'+Math.min(item.paragraphs.length-1,Math.max(0,memory.positions[item.id])))?.scrollIntoView({block:'center'})}>回到上次記錄的位置</button>}
 <p className="voice-note">閱讀位置會自動記在這個瀏覽器；下次可按「回到上次記錄的位置」。</p><article>{item.paragraphs.map((p,i)=><section className="book-paragraph" id={'book-p-'+i} key={i}><p data-speech-id={'book-p-'+i}>{show(p)}</p></section>)}</article>
 <aside className="book-word"><h2>一個詞，一個發現</h2>{'annotated'in item?<><strong>{show(item.word)}</strong><p>{show(item.definition)}</p></>:<><strong>{item.word[0]}</strong><p>{item.word[1]}</p></>}</aside>
 <section className="book-thinking"><h2>{junior?'想一想':'故事之後，還可以想一想'}</h2><p data-speech-id="book-question">{show(item.question)}</p><SpeakButton label="聽題目" segments={say(item.question,'book-question')}/>{'options'in item?<><div className="book-options">{item.options.map((o,i)=><button key={o} aria-pressed={answer===i} onClick={()=>setAnswer(i)}>{show(o)}</button>)}</div>{answer!==null&&<p role="status">{answer===item.answer?show(item.explanation):'再回到故事找找線索，可以再試一次。'}</p>}<h3>生活小活動</h3><p>{show(item.activity)}</p></>:<p>{item.thinkingHint}</p>}</section>
 <button className="book-finish" onClick={()=>update({done:[...new Set([...memory.done,item.id])],positions:{...memory.positions,[item.id]:item.paragraphs.length-1}})}>{memory.done.includes(item.id)?'已完成閱讀 ✓':'完成閱讀'}</button>
 <details className="book-source"><summary>情境、來源與聲音說明</summary>{'fictionNote'in item&&<p>{item.fictionNote}</p>}<p>本文及情境圖為本次 AI 協助新編，未引用他人故事或真實兒童經驗；自有內容正式授權尚未選定。幾何情境圖不是科學量測圖或歷史照片。</p>{item.sources.map(s=><p key={s.url}><a href={s.url} target="_blank" rel="noreferrer">{s.title}</a> · 查核 {s.checkedAt}</p>)}<p>朗讀使用既有 Web Speech API，沒有下載的聲音素材、付費語音 API 或額外音檔。</p></details><a className="book-back" href={junior?'#junior':'#stories'}>回目錄，挑下一篇 →</a></main>}
 <footer className="book-footer">問號星球 · 免費免登入 · <a href="#about">內容與權利</a> · <a href="./THIRD-PARTY-NOTICES.txt">第三方授權</a></footer></div>
}

